name: Build and Test

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:

    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up CMake
      uses: jwlawson/actions-setup-cmake@v1
      with:
        cmake-version: 3.20

    - name: Set up Ninja
      uses: actions/setup-python@v4
      with:
        python-version: 3.x

    - name: Configure (Debug)
      run: cmake --preset debug

    - name: Build (Debug)
      run: cmake --build --preset debug

    - name: Run executable (Linux only)
      if: matrix.os == 'ubuntu-latest'
      run: ./build/afazer --ajuda